### ISSUE TITLE
data-fns module没有导入

### ISSUE THREAD

**Issue by chasel** [LianjiaTech/fee#7]
按照文档启动项目后，进行注册和登录，抛出以下异常

[2019-07-19 17:35:21.619]-[runtime] info信息不是标准json
[2019-07-19 17:35:21.658]-[runtime] error.massage =>Cannot read property 'getUnixTime' of undefined

error.stack =>TypeError: Cannot read property 'getUnixTime' of undefined
    at Object.<anonymous> (/home/alain/Developer/web/fee/server/dist/model/project/user.js:95:34)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/alain/Developer/web/fee/server/dist/model/project/user.js:20:103)
    at _next (/home/alain/Developer/web/fee/server/dist/model/project/user.js:22:194)
    at /home/alain/Developer/web/fee/server/dist/model/project/user.js:22:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/alain/Developer/web/fee/server/dist/model/project/user.js:22:97)
    at Object._register (/home/alain/Developer/web/fee/server/dist/model/project/user.js:143:20)
    at Object.register (/home/alain/Developer/web/fee/server/dist/model/project/user.js:60:20)
    at /home/alain/Developer/web/fee/server/dist/routes/api/user/index.js:227:45
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/alain/Developer/web/fee/server/dist/routes/api/user/index.js:32:103)
    at _next (/home/alain/Developer/web/fee/server/dist/routes/api/user/index.js:34:194)
    at /home/alain/Developer/web/fee/server/dist/routes/api/user/index.js:34:364
    at new Promise (<anonymous>)
    at /home/alain/Developer/web/fee/server/dist/routes/api/user/index.js:34:97 => {"method":"func.catch.e","path":"/home/alain/Developer/web/fee/server/dist/library/utils/modules/router_config_builder.js","line":"33","pos":"25","file":"router_config_builder.js"}

node版本: 8.14.0
系统:ubuntu 16.04 LTS
访问浏览器: Mozilla Firefox for Ubuntu 1.0 & Chromium Version 74

![Screenshot from 2019-07-19 17-50-52](https://user-images.githubusercontent.com/1614604/61527151-662e6b80-aa4e-11e9-88e7-54b0af93cf5a.png)

**Comment by chasel** [comment]
是date-fns 的问题，在beat2时修改了导出方式
把
`import dateFns from 'date-fns'`
暂时改为
`import * as dateFns from 'date-fns'`

因为使用的是beat版本，需要关注 date-fns的最新变更
